# Generated by Django 6.0.5 on 2026-05-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hostel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "hostel_type",
                    models.CharField(
                        choices=[
                            ("boys", "Boys"),
                            ("girls", "Girls"),
                            ("mixed", "Mixed"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "price_per_month",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("total_rooms", models.PositiveIntegerField()),
                ("available_rooms", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("has_wifi", models.BooleanField(default=False)),
                ("has_parking", models.BooleanField(default=False)),
                ("has_laundry", models.BooleanField(default=False)),
                ("has_hot_water", models.BooleanField(default=False)),
                ("has_cctv", models.BooleanField(default=False)),
                ("has_kitchen", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="HostelImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="hostels/")),
                ("is_primary", models.BooleanField(default=False)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
