# Generated by Django 6.0.5 on 2026-06-03 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostels", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hostel",
            name="admission_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="hostel",
            name="room_type",
            field=models.CharField(
                choices=[
                    ("1_seater", "1 Seater (Single Room)"),
                    ("2_seater", "2 Seater (Shared - 2 Beds)"),
                    ("3_seater", "3 Seater (Shared - 3 Beds)"),
                    ("4_seater", "4 Seater (Shared - 4 Beds)"),
                ],
                default="1_seater",
                max_length=20,
            ),
        ),
    ]
