# Generated by Django 6.0.5 on 2026-06-05 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostels", "0003_hostel_admission_fee_hostel_room_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="hostel",
            name="contact_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="hostel",
            name="has_meals",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="hostel",
            name="has_power_backup",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="hostel",
            name="has_study_room",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="hostel",
            name="hostel_rules",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hostel",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="hostel",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="hostel",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="hostel",
            name="minimum_stay",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "1 Month"),
                    (3, "3 Months"),
                    (6, "6 Months"),
                    (12, "1 Year"),
                ],
                default=1,
            ),
        ),
        migrations.AddField(
            model_name="hostel",
            name="nearby_landmarks",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "1 - Poor"),
                            (2, "2 - Fair"),
                            (3, "3 - Good"),
                            (4, "4 - Very Good"),
                            (5, "5 - Excellent"),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hostel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="hostels.hostel",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("hostel", "student")},
            },
        ),
    ]
