# Generated by Django 6.0.5 on 2026-05-14 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
        ("hostels", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="hostel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="hostels.hostel",
            ),
        ),
    ]
